### ISSUE TITLE
Not working out of the box

### ISSUE THREAD

**Issue by NHKK** [Angular-RU/angular-storybook-starter#2]
I cloned the repo. Did npm install then ran npm start and all of that worked but when i ran npm run storybook and opened up the page I see the following error. 
typeError: (0 , _parserTypescript2.default) is not a function.
![image](https://user-images.githubusercontent.com/18389319/53313879-740a0700-3889-11e9-9e1c-caafe721312d.png)

**Comment by klimentru1986** [comment]
Fixed. The dependencies updated.
